### ISSUE TITLE
Roundings in repay/withdraw all 

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-dao/morpho-v1#1455]
> The production tests revealed that in some cases, repaying all (with type(uint256).max) leaves 1 wei of debt on morpho-compound, and prevents a following withdraw all (with type(uint256).max)
From @Rubilmax 

Should we fix it? If yes, how?

**Comment by MerlinEgalite** [comment]
I think we can close this one, wdyt?

**Comment by Rubilmax** [comment]
Yup, this was acknowledged and we consider the ROI not interesting to implement it
